const {test}=require('node:test'),assert=require('node:assert/strict'),L=require('../static/layout.js');
const board=(w=1080,h=1080)=>({w,h,elements:Object.fromEntries([...L.keys,'logo'].map(k=>[k,{text:k==='title'?'EIN KONZERTTITEL':'',visible:k==='title',size:k==='title'?88:32,align:'left',role:'Replica LL',x:-999,y:9999,angle:0}]))});
const measure=(t,size)=>Array.from(t).length*size*.55;
test('specified safe zones',()=>{let r=L.safeRect(board());assert.deepEqual([r.top,r.right,r.bottom,r.left],[100,100,200,100]);assert.deepEqual([r.x,r.y,r.w,r.h],[100,100,880,780]);r=L.safeRect(board(1080,1920));assert.deepEqual([r.top,r.right,r.bottom,r.left],[200,100,500,100]);assert.deepEqual([r.x,r.y,r.w,r.h],[100,200,880,1220])});
test('bottom anchored box with immutable horizontal bounds',()=>{const b=board(),x=L.textLayout(b,measure);assert.equal(x.x,100);assert.equal(x.w,880);assert.equal(x.y+x.h,880);b.textBox={offset:99999};const t=L.textLayout(b,measure);assert(Math.abs(t.y-100)<1e-8);assert.equal(t.x,100);b.textBox.offset=-99;assert.equal(L.textLayout(b,measure).offset,0)});
test('word wrap, explicit breaks and long words',()=>{assert.deepEqual(L.wrap('eins zwei\ndrei',5,t=>t.length),['eins','zwei','drei']);assert.deepEqual(L.wrap('ABCDEFGHI',3,t=>t.length),['ABC','DEF','GHI']);const b=board();b.elements.title.text='Langer Konzerttitel mit vielen Wörtern '.repeat(10);const r=L.textLayout(b,measure);assert(r.records[0].lines.length>1);assert(r.records.every(e=>e.lines.every(l=>measure(l,e.size)<=r.w+.001)));assert(r.y>=r.safe.y-.001);assert(r.y+r.h<=880.001)});
test('main texts share one box; oversized content fits without loss',()=>{const b=board();for(const key of ['date','title','subtitle']){b.elements[key].visible=true;b.elements[key].text='Ein sehr langer Text '.repeat(100)}const r=L.textLayout(b,measure);assert.equal(r.mainRecords.length,3);assert(r.factor<1);for(const e of r.mainRecords){assert(e.y>=100-.001);assert(e.y+e.h<=880.001);assert.equal(e.lines.join(' ').replace(/\s/g,''),b.elements[e.key].text.replace(/\s/g,''))}});
test('copyright is vertical, bottom aligned and centered in right margin',()=>{const b=board(),e=b.elements.copyright;e.visible=true;e.text='© Musikkollegium Winterthur';const layout=L.textLayout(b,measure),copyright=layout.copyright,r=L.recordRect(copyright);assert.equal(copyright.angle,-90);assert(Math.abs(r.y+r.h-(layout.safe.y+layout.safe.h))<1e-8);assert(Math.abs(r.x+r.w/2-(layout.safe.x+layout.safe.w+layout.safe.right/2))<1e-8);assert(r.y>=layout.safe.y-1e-8)});
test('logo move, resize and rotation stay inside zone',()=>{const b=board();b.elements.logo.size=3000;b.elements.logo.angle=47;const r=L.constrainLogo(b,3);assert(r.x>=100-1e-8&&r.y>=100-1e-8);assert(r.x+r.w<=980+1e-8&&r.y+r.h<=880+1e-8)});
