'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const express = require('express');
const studio = require('./studio');

test('Local editor: revision checks, exact preview, host protection and real Git publication', async t => {
    const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'noe-cms-test-'));
    const root = path.join(temp, 'website'); const remote = path.join(temp, 'remote.git');
    fs.mkdirSync(path.join(root, 'portfolio/projekte'), { recursive: true });
    const initial = JSON.stringify([{ id: 'example', title: 'Original', blocks: [] }]);
    fs.writeFileSync(path.join(root, 'portfolio/projekte/designs.json'), initial);
    fs.writeFileSync(path.join(root, 'index.html'), '<!doctype html><html><body><h1>Unverändert</h1></body></html>');
    fs.writeFileSync(path.join(root, 'portfolio/projekte/design.html'), '<!doctype html><html><body><script src="design.js"></script></body></html>');
    const git = (...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore','pipe','pipe'] }).trim();
    execFileSync('git', ['init', '--bare', remote], { stdio:'ignore' });
    git('init', '-b', 'main'); git('config', 'user.name', 'CMS Test'); git('config', 'user.email', 'test@example.invalid'); git('add', '.'); git('commit', '-m', 'Initial'); git('remote', 'add', 'origin', remote); git('push', '-u', 'origin', 'main');
    const app = express(); studio(app, root);
    const server = await new Promise(resolve => { const server = app.listen(0, '127.0.0.1', () => resolve(server)); });
    t.after(() => { server.close(); fs.rmSync(temp, { recursive: true, force: true }); });
    const origin = 'http://127.0.0.1:' + server.address().port;
    const request = async (url, body, method='POST', extra={}) => {
        const response = await fetch(origin+url, body===undefined?{headers:extra}:{method,headers:{'Content-Type':'application/json',Origin:origin,'X-CMS-Token':token,...extra},body:JSON.stringify(body)});
        return { status:response.status, body:await response.json() };
    };
    const token = (await request('/api/studio/session')).body.token;
    assert.equal(await new Promise(resolve=>require('http').get(origin+'/api/studio/session',{headers:{host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);})),403);
    assert.equal((await request('/api/studio/preview',{id:'a',type:'design',data:[]},'POST',{'X-CMS-Token':''})).status,403);
    assert.equal((await request('/api/studio/preview',{id:'a',type:'design',data:[]},'POST',{Origin:'https://evil.example'})).status,403);
    const loaded = (await request('/api/studio/content/design')).body;
    const draft = [{ id:'example', title:'Entwurf', blocks:[] }];
    assert.equal((await request('/api/studio/preview',{id:'test-preview',type:'design',data:draft})).status,200);
    assert.deepEqual((await request('/preview/test-preview/portfolio/projekte/designs.json')).body,draft);
    assert.equal(fs.readFileSync(path.join(root,'portfolio/projekte/designs.json'),'utf8'),initial);
    const originalHtml = fs.readFileSync(path.join(root,'portfolio/projekte/design.html'),'utf8');
    assert.equal(await (await fetch(origin+'/preview/test-preview/portfolio/projekte/design.html?example')).text(),originalHtml);
    assert.equal((await request('/preview/test-preview/portfolio-manager/server.js')).status,403);
    assert.equal((await request('/api/studio/page?file=../secret.html')).status,400);
    fs.symlinkSync(temp,path.join(root,'outside'));
    assert.equal((await request('/api/studio/page?file=outside/secret.html')).status,400);
    fs.unlinkSync(path.join(root,'outside'));
    const page=(await request('/api/studio/page?file=index.html')).body;
    assert.equal((await request('/api/studio/preview',{id:'page-preview',file:'index.html',html:'<html><body>Draft page</body></html>'})).status,200);
    assert.equal(await (await fetch(origin+'/preview/page-preview/index.html')).text(),'<html><body>Draft page</body></html>');
    assert.equal(fs.readFileSync(path.join(root,'index.html'),'utf8'),page.html);
    assert.equal((await request('/api/studio/page',{file:'index.html',html:page.html,revision:'wrong'},'PUT')).status,409);
    const saved = await request('/api/studio/content/design',{data:draft,revision:loaded.revision},'PUT');
    assert.equal(saved.status,200);
    assert.equal((await request('/api/studio/content/design',{data:draft,revision:loaded.revision},'PUT')).status,409);
    assert.equal((await request('/api/studio/content/design',{data:[...draft,...draft],revision:saved.body.revision},'PUT')).status,400);
    let state = (await request('/api/studio/git')).body;
    assert.deepEqual(state.changes.map(c=>c.file),['portfolio/projekte/designs.json']);
    assert.equal(state.changes[0].state,' M');
    // A file not in the publication scope remains untouched and uncommitted.
    fs.mkdirSync(path.join(root,'portfolio-manager')); fs.writeFileSync(path.join(root,'portfolio-manager','notes.txt'),'private tool change');
    state = (await request('/api/studio/git')).body;
    assert.equal(state.changes.find(c=>c.file==='portfolio-manager/notes.txt').allowed,false);
    assert.equal((await request('/api/publish',{signature:'stale',files:[],message:'No'})).status,409);
    const message='Literal $(touch SHOULD_NOT_EXIST) `touch ALSO_NOT` "quote"';
    const published=await request('/api/publish',{signature:state.signature,files:['portfolio/projekte/designs.json'],message});
    assert.equal(published.status,200,JSON.stringify(published.body));
    assert.equal(git('log','-1','--format=%B'),message);
    assert.equal(git('rev-parse','HEAD'),git('rev-parse','origin/main'));
    assert.equal(fs.existsSync(path.join(root,'SHOULD_NOT_EXIST')),false);
    assert.equal(git('status','--porcelain','--untracked-files=all'),'?? portfolio-manager/notes.txt');
    // Push-only retry must still transfer an existing local commit.
    fs.writeFileSync(path.join(root,'index.html'),'<html><body>Second</body></html>');git('add','index.html');git('commit','-m','Pending');
    state=(await request('/api/studio/git')).body;assert.equal(state.ahead,1);
    assert.equal((await request('/api/publish',{signature:state.signature,files:[],message:'Push retry'})).status,200);
    assert.equal(git('rev-parse','HEAD'),git('rev-parse','origin/main'));
    state=(await request('/api/studio/git?refresh=1')).body;
    assert.equal(state.pending.length,0);assert.equal(state.ahead,0);assert.equal(state.pushed[0].subject,'Pending');assert.ok(state.lastFetch);
    // CMS code belongs in publication scope too; a rejected push keeps an accurate local commit.
    fs.writeFileSync(path.join(root,'portfolio-manager','studio.js'),'// editor update');
    git('add','portfolio-manager/notes.txt');
    state=(await request('/api/studio/git')).body;
    assert.equal(state.changes.find(c=>c.file==='portfolio-manager/studio.js').allowed,true);
    const hook=path.join(remote,'hooks/pre-receive');fs.writeFileSync(hook,'#!/bin/sh\nexit 1\n',{mode:0o755});
    const rejected=await request('/api/publish',{signature:state.signature,files:['portfolio-manager/studio.js'],message:'CMS update'});
    assert.equal(rejected.status,500);
    state=(await request('/api/studio/git?refresh=1')).body;
    assert.equal(state.ahead,1);assert.equal(state.pending[0].subject,'CMS update');assert.deepEqual(state.pending[0].files,['portfolio-manager/studio.js']);
    assert.equal(state.pushed.some(c=>c.subject==='CMS update'),false);
    assert.equal(git('diff','--cached','--name-only'),'portfolio-manager/notes.txt');
    fs.unlinkSync(hook);
    const retried=await request('/api/publish',{signature:state.signature,files:[],message:''});
    assert.equal(retried.status,200);assert.equal(retried.body.state.ahead,0);assert.equal(retried.body.state.pending.length,0);assert.equal(retried.body.state.pushed[0].subject,'CMS update');
    // Photography remains editable without generating separate image pages.
    fs.writeFileSync(path.join(root,'portfolio/projekte/photography.json'),'[]');
    const photo=(await request('/api/studio/content/photography')).body;
    const album=[{id:'street',title:'Street',blocks:[{type:'gallery',items:[{id:'photo-1',title:'Bild',imageUrl:'../../images/one.jpg'}]}]}];
    assert.equal((await request('/api/studio/preview',{id:'photos',type:'photography',data:album})).status,200);
    assert.equal(fs.existsSync(path.join(root,'portfolio/projekte/image-pages.json')),false);
    assert.equal((await request('/api/studio/content/photography',{data:album,revision:photo.revision},'PUT')).status,200);
    assert.equal(fs.existsSync(path.join(root,'portfolio/projekte/image-pages.json')),false);
    assert.equal((await request('/api/studio/content/photography')).body.data[0].id,'street');
});
