const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const page=await browser.newPage();page.setDefaultTimeout(60000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 // An unavailable detector must never block importing or saving a project.
 await page.route('**/person.tflite',r=>r.abort());await page.goto(process.env.STUDIO_URL||'http://127.0.0.1:8898/');await page.locator('#startNew').click();
 await page.locator('[data-format-enabled]').nth(0).uncheck();await page.locator('[data-format-enabled]').nth(2).uncheck();const square=page.locator('[data-format]').nth(1);await square.locator('[data-format-key="w"]').fill('320');await square.locator('[data-format-key="h"]').fill('320');await square.locator('[data-format-key="top"]').fill('30');await square.locator('[data-format-key="bottom"]').fill('30');await page.locator('#setupName').fill('Testprojekt');await page.locator('#createProject').click();
 const png=await page.evaluate(()=>{const c=makeCanvas(200,200),x=c.getContext('2d');x.fillStyle='#ff0000';x.fillRect(50,50,100,100);return c.toDataURL().split(',')[1]});await page.locator('#files').setInputFiles({name:'graphic.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.waitForFunction(()=>p.boards.length===1&&!busy);assert((await page.evaluate(()=>p.images[0].subjectStatus)).includes('nicht verfügbar'));
 const results=await page.evaluate(async()=>{const b=p.boards[0];b.image.scale=.5;b.elements.logo.visible=false;for(const key of MKWLayout.keys){b.elements[key].visible=false;b.elements[key].enabled=false}const result=[];for(const format of ['jpg','png','webp'])for(const transparent of [false,true]){const settings={format,quality:85,png8:format==='png',colours:2,transparent:format!=='jpg'&&transparent};const {blob}=await encodedBoard(clone(b),settings),bitmap=await createImageBitmap(blob),c=makeCanvas(320,320);c.getContext('2d').drawImage(bitmap,0,0);result.push({format,transparent,alpha:c.getContext('2d').getImageData(0,0,1,1).data[3],mime:blob.type});bitmap.close()}return result});for(const r of results){assert.equal(r.alpha,r.format==='jpg'||!r.transparent?255:0);assert.equal(r.mime,{jpg:'image/jpeg',png:'image/png',webp:'image/webp'}[r.format])}
 await page.evaluate(()=>{p.meta.date='19.11.26';p.meta.title='Test';p.meta.code='T'});await page.locator('#export').click();await page.locator('#exportFormat').selectOption('webp');await page.locator('#exportTransparent').check();await page.waitForFunction(()=>document.querySelector('.export-size')?.dataset.bytes);
 // Folder export writes the encoded WebP bytes, and refuses an existing name.
 await page.evaluate(()=>{window.writes=[];window.existing=false;window.showDirectoryPicker=async()=>({getFileHandle:async(name,opts)=>{if(!opts?.create){if(window.existing)return {};throw new DOMException('Missing','NotFoundError')}return {createWritable:async()=>({write:async blob=>window.writes.push({name,type:blob.type,size:blob.size}),close:async()=>{},abort:async()=>{}})}}});document.querySelector('#folder').hidden=false});
 await page.locator('#folder').click();await page.waitForFunction(()=>!busy);assert.equal(await page.evaluate(()=>writes.length),1);assert.equal(await page.evaluate(()=>writes[0].type),'image/webp');await page.evaluate(()=>existing=true);await page.locator('#folder').click();await page.waitForFunction(()=>!busy);assert.equal(await page.evaluate(()=>writes.length),1);assert((await page.locator('#exportStatus').innerText()).includes('existiert'));
 await page.locator('#closeExport').click();
 // Legacy projects still open; their original board geometry is preserved.
 const legacy=await page.evaluate(async()=>{const q=clone(p);delete q.formats;for(const b of q.boards)delete b.safe;await restore(q);return {formats:p.formats,safe:MKWLayout.safeRect(p.boards[0])}});assert.equal(legacy.formats,undefined);assert(Math.abs(legacy.safe.left-100*320/1080)<1e-9);
 assert.deepEqual(errors,[]);console.log('PASS model failure fallback, JPG/PNG-8/WebP alpha, folder export/no-overwrite and legacy restore');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
