const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.STUDIO_URL||'http://127.0.0.1:8898/');await page.locator('#startNew').click();await page.locator('#createProject').click();assert((await page.locator('#setupError').innerText()).includes('Namen'));await page.locator('#setupName').fill('Sommerkonzerte');await page.locator('#setupCode').fill('F1');assert.equal(await page.locator('[data-format-enabled]:checked').count(),2);await page.screenshot({path:'/private/tmp/mkw-setup-top.png'});await page.locator('#createProject').click();await page.evaluate(()=>{MKWSubject.detect=async()=>{await new Promise(r=>setTimeout(r,1200));return[]}});await page.locator('#files').setInputFiles(process.env.FIXTURE);await page.locator('[data-import-stage="1"].active').waitFor();await page.screenshot({path:'/private/tmp/mkw-import.png'});await page.waitForFunction(()=>!busy&&p.boards.length===2);assert.equal(await page.evaluate(()=>p.meta.title),'Sommerkonzerte');assert.equal(await page.locator('.text-editor.is-empty:not([hidden])').count(),2);
await page.locator('#mainTextInput').fill('Erster Konzerttitel');assert.equal(await page.evaluate(()=>p.boards[0].elements.title.text),'ERSTER KONZERTTITEL');await page.locator('#mainTextInput').fill('');
await page.locator('canvas[data-board]').nth(1).scrollIntoViewIfNeeded();const point=await page.evaluate(()=>{const b=p.boards[1],r=textBlock(b,'title').records.find(e=>e.key==='title'),c=document.querySelector(`canvas[data-board="${b.id}"]`).getBoundingClientRect();return{x:c.left+(r.x+20)*c.width/b.w,y:c.top+(r.y+r.h/2)*c.height/b.h}});await page.mouse.click(point.x,point.y);await page.keyboard.type('Direkt nach Import');assert.equal(await page.evaluate(()=>p.boards[1].elements.title.text),'DIREKT NACH IMPORT');assert.equal(await page.evaluate(()=>step),'text');await page.locator('#mainTextInput').fill('');
await page.evaluate(()=>{if(editingText)editingText.el.blur()});await page.locator('#mainTextInput').fill('');
// First background click selects an empty board; only the second starts cropping.
await page.evaluate(()=>{chooseStep('text');selectBoard(p.boards[0].id)});
const background=await page.evaluate(()=>{const c=document.querySelectorAll('canvas[data-board]')[1].getBoundingClientRect();return{x:c.left+8,y:c.top+c.height/2}});
for(const deselected of [false,true]){if(deselected)await page.evaluate(()=>{chooseStep('text');selectBoard(null)});const before=await page.evaluate(()=>JSON.stringify(p.boards[1].image));await page.mouse.click(background.x,background.y);assert.deepEqual(await page.evaluate(()=>({step,selected:selected===p.boards[1].id,moving:!!movement})),{step:'text',selected:true,moving:false});assert.equal(await page.evaluate(()=>JSON.stringify(p.boards[1].image)),before);await page.mouse.click(background.x,background.y);assert.equal(await page.evaluate(()=>step),'crop')}
await page.evaluate(()=>chooseStep('text'));
await page.evaluate(()=>{const b=board();b.elements.date.visible=false;delete b.elements.date.enabled;syncOverlays(true)});assert(await page.locator('.text-editor[data-key=date]').isVisible());
const transparency=await page.evaluate(async()=>{const b=clone(p.boards[0]);const settings={format:'png',transparent:true,quality:90,png8:false,colours:256};const opaque=await encodedBoard(b,settings);b.image.scale=.01;const clear=await encodedBoard(b,settings);return [opaque.hasTransparency,clear.hasTransparency]});assert.deepEqual(transparency,[false,true]);assert.deepEqual(errors,[]);console.log('PASS required name, two defaults, import stages, empty and legacy text fields, actual alpha detection');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
